### ISSUE TITLE
Feature Request: Generate/Edit Masks

### ISSUE THREAD

**Issue by Enixile** [Particle1904/DatasetHelpers#10]
So far, at least one training tool, OneTrainer, supports the use of masking to exclude sections of an image from training. This is an improvement over training on blanked-out sections. The masks are PNG files with the same name as the image with suffix "-masklabel" where white is trained and black is not trained. They can be auto generated or manually edited. It would be helpful to include that functionality in this all-in-one tool.

**Comment by Particle1904** [comment]
Very interesting request but this is the kind of thing that 99% of people wont ever use. I remember when AI Casanova implemented that feature in his training notebook but it never became something that people use in their datasets even tho its something that can improve the models.

I'll think about it and do some research since I have no idea about how to implement such feature. No promises tho.
