### ISSUE TITLE
Feature Request: Advanced image filtering

### ISSUE THREAD

**Issue by Enixile** [Particle1904/DatasetHelpers#12]
The Sort Images tab allows the user to filter images based on a specified resolution, which can be a rough approximation of quality. However, there are many other quality metrics that would be helpful for more advanced filtering, especially with large datasets. For example, bluriness, artifacts, color presence, watermarks, and similarity. For similarity, it could do basic deduplication or put photos above a certain similarity threshold into a sub-folder for review. Photos with the same clothing, lighting, etc. can reduce model flexibility.

**Comment by Particle1904** [comment]
This was always in my plans for the tools but that's a VERY hard thing to add.
Best way I found is to use AI models specifically trained for image metrics, but converting models to .onnx format (and for now that's the only feasible way to run models with C#) is usually A LOT of work and weeks of pulling my hair out.

Finding duplicates and similar images is a lot easier but its still quite a bit of work, so not planned for now since I'm not really doing a lot of AI stuff anymore. I suggest trying the AllDup software for that functionality, for now.
