### ISSUE TITLE
Could you add Z3D-E621-Convnext

### ISSUE THREAD

**Issue by Bercraft** [Particle1904/DatasetHelpers#15]
Could you add the E621 model in [https://huggingface.co/toynya/Z3D-E621-Convnext/tree/main](url)
it is an interrogator, useful links can be->
[https://github.com/picobyte/stable-diffusion-webui-wd14-tagger](url)

thank you.

**Comment by Particle1904** [comment]
By inspecting the model architecture using Netron.app, it appears that the inputs and outputs align in a 1:1 ratio with WD 1.4. Integrating support for this model should be straightforward. You can potentially modify Z3D-E621 files by renaming the .onnx model to 'wdModel.onnx' and the .csv to 'wdTags.cs.' Additionally, it's necessary to edit the tags .csv file by removing columns 1, 3, and 4, leaving only the tags with one tag per line.

If I continue to add models, the download size for each release increases by over 350mb. While I could make it modular and instruct users to download and set it up themselves, my goal is to keep the process as user-friendly as possible. However, I'm open to considering _"official"_ support if you can provide compelling reasons for its inclusion; I personally don't see one... I'm not currently developing the tools anymore because I've moved away from AI and Stable Diffusion.

**Comment by Particle1904** [comment]
There's literally 0 information about the model in the huggingface .README.
What is it supposed to do, how its better than other models, no benchmarks.

**Comment by Particle1904** [comment]
My plan was to do some gamedev stuff but I ended up spending 3 hours implementing Z3D E621 model and doing some code clean up.

I've added support for the model and also support for automatically downloading model files from HuggingFace when necessary: https://github.com/Particle1904/DatasetHelpers/releases/tag/v2.2.0
