### ISSUE TITLE
Hi, I am having a lot of trouble with the auto model downloading for tag generation, I always get timed out.

### ISSUE THREAD

**Issue by FozeAhmad9999** [Particle1904/DatasetHelpers#18]
I am not really tech savy , so this probably an issue with settings on my pc rather than, the application, but the inclusion of the models with the app would be really solve this problem  even tho it will require more disk space, i tried downloading and renaming the models but that didnt work for me either

**Comment by Particle1904** [comment]
Wait, really? I did not expect that to be a problem. Did the application save a log file? Do you have a slow internet connection?
I opted for making it automatically download to make it easier for me and for users; some people complained that the download sizes were getting too big.
I don't have to upload 2gb+ for each release and users don't need to download 2gb+ for each release.
The files are all publicly available in this HuggingFace repository that I made for the automatic download feature: https://huggingface.co/Crowlley/DatasetToolsModels/tree/main

In order to properly integrate the .onnx model files (and the .csv files) into the application, please ensure that you place them inside the "models" folder. The "models" folder should be located in the root directory of the application, which is where the "DatasetProcessorDesktop.exe" file is located. If the "models" folder does not exist, please create it manually in the same directory as the "DatasetProcessorDesktop.exe" file. Make sure to maintain the original file names and extensions when placing the .onnx model files (and the .csv file) into the "models" folder. This will enable the application to access and utilize the models seamlessly.

**Comment by Particle1904** [comment]
Looks like it timed out, not sure what I can do about it other than increasing the timeout from 100 seconds (the default value) to 5 minutes. I imagine its something to do with your internet speed.
The app started the download and then it stopped or it didn't even started the download? Did it create a file in the models folder at all?

**Comment by FozeAhmad9999** [comment]
download never started, I had a friend install on his pc, he does have very good internet it worked fine for him

**Comment by Particle1904** [comment]
I'm not sure what I can do about it. I'll try to get more information from the exception when it happens so I can understand better what is the problem. For now I'll increase the timeout to 5 minutes. 
I hope having access to the HuggingFace repository is enough of a temporary solution for now.
Also found out that the Generator Page lets you select the Yolo model but the Yolo model isn't for generating tags; I'll fix that too.

**Comment by FozeAhmad9999** [comment]
oh and the excel files with the tags download with out a hitch, and yes i have down loaded the models, thank you
